version: "3"

services:
    hub:
        image: selenium/hub:3.8.1-francium
        ports:
            - "4444:4444"
        
    chrome:
        image: selenium/node-chrome:3.8.1-francium
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - hub
        environment:
            HUB_HOST: hub

    firefox:
        image: selenium/node-firefox:3.8.1-francium
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - hub
        environment:
            HUB_HOST: hub